# Generated by Django 3.2 on 2021-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hadithi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('story', models.TextField()),
                ('viewers', models.IntegerField(null=True)),
                ('positive_clicks', models.IntegerField(null=True)),
                ('negative_clicks', models.IntegerField(null=True)),
                ('category', models.ManyToManyField(to='homepage.MainTag')),
                ('tag', models.ManyToManyField(null=True, to='homepage.SubTag')),
            ],
        ),
    ]
