# Generated by Django 3.2 on 2021-04-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hadithi',
            options={'verbose_name': 'Hadithi', 'verbose_name_plural': 'Stories'},
        ),
    ]
