# Generated by Django 3.2 on 2021-05-02 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0005_auto_20210502_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadithi',
            name='negative_clicks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hadithi',
            name='owner',
            field=models.ForeignKey(default='Michael Graff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hadithi',
            name='positive_clicks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hadithi',
            name='viewers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
