# Generated by Django 3.2 on 2021-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_hadithi_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('rated', models.TextField()),
                ('posted', models.DateTimeField()),
                ('tags', models.TextField()),
                ('story', models.TextField()),
            ],
            options={
                'verbose_name': 'Demo',
                'verbose_name_plural': 'DemoStories',
            },
        ),
    ]
