# Generated by Django 3.2 on 2021-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_demostories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demostories',
            name='posted',
            field=models.TextField(),
        ),
    ]
